# Base configs
baseurl: "https://saurabac.github.io/photography"
#baseurl: "" # Comment the above line and uncomment this to test the website locally
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Saurab Chhachhi"
subtitle: " "
author: "Saurab Chhachhi"
header:
 title: "Photography"
 subtitle: "by Saurab Chhachhi"
footer:
 name: "Hey there, my name is Saurab"
 bio: "I am a data scientist who enjoys nature and photography."
 github: "Want a website like this for yourself for free? Just <a href=\"https://github.com/ramswaroop/photography\">fork this repo on github</a> ;)"
web_design: "AJ"
# Configure which exif data to display
# Tag is the actual exif tag, icon is a fontawesome icon. Use JSON notation without line breaks
exif: '[{"tag": "Model", "icon": "camera-retro"}, {"tag": "FNumber", "icon": "dot-circle-o"}, {"tag": "ExposureTime", "icon": "clock-o"}, {"tag": "ISOSpeedRatings", "icon": "info-circle"}]'
social_urls:
  twitter: #"https://www.twitter.com/ram__patra"
  instagram: #"https://www.instagram.com/ram_patra"
  dribbble: #"https://dribbble.com/rampatra"
  linkedin: "https://www.linkedin.com/in/saurab-chhachhi-4a627b69"
  github: "https://www.github.com/saurabac"
